/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthBannedRouteImport } from './routes/auth/banned'
import { Route as AppStartRouteImport } from './routes/app/start'
import { Route as AppListsRouteRouteImport } from './routes/app/lists/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBannedRoute = AuthBannedRouteImport.update({
  id: '/auth/banned',
  path: '/auth/banned',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStartRoute = AppStartRouteImport.update({
  id: '/app/start',
  path: '/app/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AppListsRouteRoute = AppListsRouteRouteImport.update({
  id: '/app/lists',
  path: '/app/lists',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/lists': typeof AppListsRouteRoute
  '/app/start': typeof AppStartRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/lists': typeof AppListsRouteRoute
  '/app/start': typeof AppStartRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/lists': typeof AppListsRouteRoute
  '/app/start': typeof AppStartRoute
  '/auth/banned': typeof AuthBannedRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/lists'
    | '/app/start'
    | '/auth/banned'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/lists'
    | '/app/start'
    | '/auth/banned'
    | '/auth/sign-in'
    | '/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/app/lists'
    | '/app/start'
    | '/auth/banned'
    | '/auth/sign-in'
    | '/auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppListsRouteRoute: typeof AppListsRouteRoute
  AppStartRoute: typeof AppStartRoute
  AuthBannedRoute: typeof AuthBannedRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/banned': {
      id: '/auth/banned'
      path: '/auth/banned'
      fullPath: '/auth/banned'
      preLoaderRoute: typeof AuthBannedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/start': {
      id: '/app/start'
      path: '/app/start'
      fullPath: '/app/start'
      preLoaderRoute: typeof AppStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/lists': {
      id: '/app/lists'
      path: '/app/lists'
      fullPath: '/app/lists'
      preLoaderRoute: typeof AppListsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppListsRouteRoute: AppListsRouteRoute,
  AppStartRoute: AppStartRoute,
  AuthBannedRoute: AuthBannedRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
